'use strict';
const $=id=>document.getElementById(id), key='luminis_med16_2_02_events_v1';
const fmt=n=>Number.isInteger(n)?String(n):Number(n.toFixed(3)).toString();
let mode='init',events=[],latestId=null;
function localDate(d){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
try{let old=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(old))events=old.filter(e=>e&&Number.isFinite(Date.parse(e.time)))}catch(e){$('status').textContent='Stored events could not be read. Export or clear browser data before creating a new log.'}
function switchMode(m){mode=m;for(let x of ['init','adjust','restart']){$(x+'Fields').classList.toggle('hidden',x!==m);$(x+'Tab').classList.toggle('active',x===m)}$('weightField').classList.toggle('hidden',m==='restart');$('output').classList.add('hidden');$('save').disabled=true;latestId=null}
for(let m of ['init','adjust','restart'])$(m+'Tab').onclick=()=>switchMode(m);
for(let el of $('form').elements)el.addEventListener('input',()=>{$('save').disabled=true;latestId=null});
function num(id){let el=$(id),n=Number(el.value);if(el.value.trim()===''||!Number.isFinite(n)||(id==='potassium'?n<0:n<=0)||n>Number(el.max)||(id==='minutes'&&!Number.isInteger(n)))throw Error(`Enter a valid ${el.previousElementSibling.textContent}.`);return n}
function run(){if(mode==='init')return init({weight:num('weight'),bg:num('initBG'),potassium:num('potassium')});if(mode==='adjust')return adjust({weight:num('weight'),bg:num('current'),previous:num('previous'),rate:num('rate'),phase:Number($('phase').value),minutes:num('minutes')});return restart({bg:num('recheckBG'),lastRate:num('lastRate'),reason:$('reason').value})}
function render(x){let o=$('output');o.className='card';let box=document.createElement('div');box.className='result '+x.type;let h=document.createElement('h2');h.textContent=x.title;box.append(h);if(x.newRate!==null){let d=document.createElement('div');d.className='big';d.textContent=fmt(x.newRate)+' units/hr';box.append(d)}let ul=document.createElement('ul');for(let n of x.notes){let li=document.createElement('li');li.textContent=n;ul.append(li)}box.append(ul);o.replaceChildren(box);o.scrollIntoView({behavior:'smooth',block:'nearest'})}
function warningLines(x){if(['stop','hold','review'].includes(x.type))return [x.title,...x.notes];return x.notes.filter(n=>/notify provider|notify physician|provider review|maximum|no rounding|ensure dextrose|selected for review/i.test(n))}
function popup(x){let lines=warningLines(x);if(!lines.length)return;let list=$('warningItems');list.replaceChildren();for(let t of lines){let li=document.createElement('li');li.textContent=t;list.append(li)}$('warningPanel').className=['stop','hold'].includes(x.type)?'modal-stop':'modal-review';if(typeof $('warningDialog').showModal==='function')$('warningDialog').showModal();else alert(lines.join('\n\n'))}
$('dismissWarning').onclick=()=>$('warningDialog').close();
function snapshot(x){let prior=mode==='adjust'?$('rate').value:mode==='restart'?$('lastRate').value:'';let rate=x.newRate===null?'':fmt(x.newRate);return {mode,weight:mode==='restart'?'':$('weight').value,phase:mode==='adjust'?$('phase').value:mode==='init'?(Number($('initBG').value)<250?'2':'1'):'2',previousBG:mode==='adjust'?$('previous').value:'',currentBG:mode==='init'?$('initBG').value:mode==='adjust'?$('current').value:$('recheckBG').value,priorRate:prior,potassium:mode==='init'?$('potassium').value:'',minutes:mode==='adjust'?$('minutes').value:'',title:x.title,recommendation:rate,rateChange:prior!==''&&rate!==''?fmt(Number(rate)-Number(prior)):'',actualRate:'',note:'',status:x.type,details:x.notes.join(' | '),source:'automatically saved calculation'} }
function persist(){try{localStorage.setItem(key,JSON.stringify(events));return true}catch(e){$('status').textContent='Could not save in browser storage. Export the current log now; entries may be lost on reload.';return false}}
function autoSave(x){let entry=snapshot(x),now=Date.now();entry.id='calc-'+now+'-'+Math.random().toString(36).slice(2,10);entry.time=new Date(now).toISOString();events.push(entry);events.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));let stored=persist();latestId=entry.id;$('time').value=localDate(new Date(entry.time));$('actual').value='';$('note').value='';$('save').disabled=false;if(stored)$('status').textContent=`Calculation automatically saved at ${new Date(entry.time).toLocaleString()}. ${events.length} event(s) in this browser.`;report()}

$('form').onsubmit=e=>{e.preventDefault();try{let x=run();render(x);autoSave(x);popup(x)}catch(err){render({type:'review',title:'Check input',newRate:null,notes:[err.message]});$('save').disabled=true;latestId=null;popup({type:'review',title:'Check input',notes:[err.message]})}};
$('save').onclick=()=>{let entry=events.find(e=>e.id===latestId);if(!entry){$('status').textContent='Calculate again to select an event for updating.';return}let actual=$('actual').value.trim();if(actual!==''&&(!Number.isFinite(Number(actual))||Number(actual)<0||Number(actual)>30)){$('status').textContent='Actual rate must be between 0 and 30 units/hr.';return}entry.actualRate=actual;entry.note=$('note').value.trim().slice(0,160);persist();$('status').textContent='Actual rate and note updated on the latest calculated event.';report()};
$('clear').onclick=()=>{if(events.length&&!confirm(`Clear ${events.length} saved event(s)? Export first if needed.`))return;events=[];persist();latestId=null;$('save').disabled=true;$('time').value='';$('status').textContent='Log cleared; new session started.';report()};
function windowEvents(){let now=Date.now(),start=now-Number($('hours').value)*3600000;return events.filter(e=>Date.parse(e.time)>=start&&Date.parse(e.time)<=now)}
function report(){let chosen=windowEvents(),body=$('reportBody');body.replaceChildren();let bg=chosen.map(e=>Number(e.currentBG)).filter(n=>Number.isFinite(n)&&n>0),p=document.createElement('p');p.className='small';p.textContent=`Report ending ${new Date().toLocaleString()}. ${chosen.length} saved calculations, ${bg.length} BG readings, ${bg.filter(n=>n<100).length} BG readings below 100 mg/dL. Logged readings are not continuous time in range.`;body.append(p);$('exportStatus').textContent=`${chosen.length} events in selected window; ${events.length} total saved in this browser. ${chosen.length===0&&events.length?'Choose a longer window or Export all CSV.':chosen.length===0?'Calculate a result first to create an event.':''}`;if(!chosen.length)return;let scroll=document.createElement('div');scroll.className='scroll';let table=document.createElement('table');let head=document.createElement('tr');for(let v of ['Time','Table','BG','Prior BG','Prior rate','Recommended change','Calculated result','Actual rate','Note']){let th=document.createElement('th');th.textContent=v;head.append(th)}table.append(head);for(let e of chosen){let tr=document.createElement('tr');for(let v of [new Date(e.time).toLocaleString(),e.phase,e.currentBG,e.previousBG,e.priorRate,e.rateChange==null||e.rateChange===''?'':e.rateChange+' units/hr',e.title+(e.recommendation?' — '+e.recommendation+' units/hr':''),e.actualRate,e.note]){let td=document.createElement('td');td.textContent=v==null?'':v;tr.append(td)}table.append(tr)}scroll.append(table);body.append(scroll);let note=document.createElement('p');note.className='small';note.textContent='This records calculations automatically, not pump changes or medication administration. Actual rate is entered separately and is not verified against the MAR.';body.append(note)}
$('hours').onchange=report;$('refresh').onclick=report;$('print').onclick=()=>{report();window.print()};
function safeCSV(v){let s=String(v==null?'':v);if(/^\s*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}function csv(items,name){if(!items.length){$('exportStatus').textContent=events.length?`No events in the selected ${$('hours').value}-hour window. Choose a longer window or use Export all CSV.`:'No events have been saved in this browser. Calculate a result first; no CSV was downloaded.';return}let cols=['time','source','mode','weight','phase','potassium','previousBG','currentBG','minutes','priorRate','rateChange','title','recommendation','actualRate','status','details','note'];let text=[cols.map(safeCSV).join(','),...items.map(e=>cols.map(k=>safeCSV(e[k])).join(','))].join('\r\n');let url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();$('exportStatus').textContent=`Downloaded ${items.length} event(s) to ${name}.`;setTimeout(()=>URL.revokeObjectURL(url),60000)}
$('allCSV').onclick=()=>csv(events,'luminis-insulin-all-events.csv');$('windowCSV').onclick=()=>csv(windowEvents(),`luminis-insulin-${$('hours').value}h.csv`);report();
