/* LH MED16.2.02 Attachment 1, supplied PDF. Pure calculation functions for review. */
const BANDS={small:{label:'≤60 kg',cap1:6.3,cap2:2.3},middle:{label:'>60 to <100 kg',cap1:10.5,cap2:3.8},large:{label:'≥100 kg',cap1:14,cap2:5}};
// Each cell is the signed rate change (units/hr). Column order: >25 rise, within ±25, 26–50 fall, >50 fall.
const TABLE1={small:[[2.5,2,1,.5],[2,1.5,.5,.3],[1.5,1,.3,0],[1,.5,0,0],[.5,.3,0,-2]],middle:[[3.5,2.5,1.5,1],[2.5,2,1,.5],[2,1.5,.5,0],[1.5,1,0,0],[1,.5,0,-2.5]],large:[[5,4,2,1.5],[4,3,1.5,1],[3,2,1,0],[2,1.5,0,0],[1.5,1,0,-3]]};
const TABLE2={small:[[1,.5,0,0],[.5,.2,0,-.5],[.2,0,-.5,-.7],null,[0,-.2,-.7,-1],[-.2,-.5,-1,-1.2]],middle:[[1.5,1,0,0],[1,.5,0,-1],[.5,0,-1,-1.5],null,[0,-.5,-1.5,-2],[-1,-1,-2,-2.5]],large:[[1.5,1,0,0],[1,.5,0,-1.5],[.5,0,-1,-2],null,[0,-.5,-1.5,-2.5],[-.5,-1,-2,-3]]};
function band(weight){return weight<=60?'small':weight<100?'middle':'large'}
function roundTenth(n){return Math.round((n+Number.EPSILON)*10)/10}
function response(type,title,newRate=null,notes=[]){return {type,title,newRate,notes}}
function init({weight,bg,potassium}){const b=band(weight),phase=bg<250?2:1,cap=phase===1?BANDS[b].cap1:BANDS[b].cap2,raw=weight*(phase===1?.14:.05);if(potassium<3.3)return response('stop','DO NOT START insulin',null,['Potassium <3.3 mEq/L: page provider.']);if(bg<100)return response('hold','Do not initiate: BG below 100 mg/dL',null,['Table 2 says hold and recheck BG after 1 hour; ensure dextrose-containing IV fluids are running. Confirm provider direction.']);let rate=phase===1?Math.min(roundTenth(raw),cap):Math.min(raw,cap);let notes=[`Weight band ${BANDS[b].label}; Table ${phase}; ${phase===1?'0.14':'0.05'} units/kg/hr = ${raw.toFixed(3)} units/hr; cap ${cap} units/hr.`,phase===1?'Table 1 initial rate rounded to nearest 0.1 unit/hr.':'Table 2 does not give a rounding increment; confirm pump setting.', 'Check BG hourly; document rate changes on MAR.'];if(phase===2)notes.push('Ensure dextrose-containing fluids are running.');if(weight===60)notes.push('Exactly 60 kg appears in overlapping printed headings; ≤60 kg band selected for review.');if(weight===100)notes.push('Exactly 100 kg appears in overlapping printed headings; ≥100 kg band selected for review.');return response('rate','Initial infusion',rate,notes)}
function row1(bg){return bg>450?0:bg>=401?1:bg>=351?2:bg>=301?3:bg>=250?4:-1}
function row2(bg){return bg>300?0:bg>=250?1:bg>=201?2:bg>=150?3:bg>=125?4:bg>=100?5:-1}
function deltaCol(change){return change>25?0:change>=-25?1:change>=-50?2:3}
function adjust({weight,bg,previous,rate,phase,minutes}){let b=band(weight),change=bg-previous,notes=[`Weight band ${BANDS[b].label}; previous BG ${previous}, current BG ${bg}; change ${change>=0?'+':''}${change} mg/dL over ${minutes} minutes.`];if(weight===100)notes.push('Exactly 100 kg appears in two headings; ≥100 kg band selected for review.');if(bg<100)return response('hold','HOLD infusion',null,[...notes,'Recheck BG in 1 hour. Ensure dextrose-containing IV fluids are running.','If BG >200 mg/dL, restart at 50% of the rate before BG dropped below 100.']);if(minutes!==60)return response('review','Check BG timing',null,[...notes,'Protocol specifies BG checks every 1 hour and describes the large-drop rule per hour. This calculator requires checks recorded 60 minutes apart for automated titration.']);if(change===-150)return response('review','Exact 150 mg/dL drop needs review',null,[...notes,'Main instructions say more than 150 mg/dL, while table headers say 150 mg/dL or more. Confirm which rule applies with provider.']);if(change< -150)return response('review','Large BG drop: decrease rate by 50% and notify provider',rate/2,[...notes,'Table headers specify 50% of current rate when BG drops 150 mg/dL or more in 1 hour. Main text says “decrease rate of change ... by 50%”; reconcile against current order.','Notify provider; confirm new pump setting and dextrose fluids.']);if(phase===1&&bg<250){let base=Math.min(weight*.05,BANDS[b].cap2);return response('review','Switch to Table 2: redose infusion',base,[...notes,`0.05 units/kg/hr = ${(weight*.05).toFixed(3)} units/hr; maximum ${BANDS[b].cap2} units/hr. This is a new Table 2 base rate, not a Table 1 increment.`,'Ensure dextrose-containing fluids are running. Table 2 gives no rounding rule; confirm pump setting.']);}if(phase===1&&bg>=250){let row=row1(bg),diff=TABLE1[b][row][deltaCol(change)];return doseResult(rate,diff,notes,'Table 1')}if(phase===2){let row=row2(bg);if(row===3)return response('rate','Continue current rate',rate,[...notes,'Table 2: BG 150–200 mg/dL, continue current rate.','Ensure dextrose-containing fluids are running.']);let diff=TABLE2[b][row][deltaCol(change)];return doseResult(rate,diff,[...notes,'Ensure dextrose-containing fluids are running.'],'Table 2')}return response('review','Confirm table selection',null,notes)}
function doseResult(rate,diff,notes,table){let next=rate+diff;notes.push(`${table}: ${diff>=0?'+':''}${diff} units/hr from ${rate} units/hr = ${next.toFixed(3)} units/hr.`);if(next<0)return response('hold','HOLD infusion for 1 hour',null,[...notes,'Calculated reduction would produce a negative rate. Recheck BG after 1 hour, then resume per Table 2; no automatic restart rate specified.']);if(next===0)return response('review','Zero-rate boundary needs provider review',null,[...notes,'Protocol only states what to do when the calculation is negative; it does not specify whether zero should be treated as a hold.']);if(next>30)return response('review','Calculated rate exceeds maximum 30 units/hr',null,[...notes,'Do not exceed 30 units/hr; obtain provider direction.']);if(next>25)notes.push('Rate >25 units/hr: notify physician.');notes.push('Check BG hourly and document each insulin infusion rate change on MAR.');return response('rate',diff===0?'No rate change':diff>0?'Increase infusion':'Decrease infusion',next,notes)}
function restart({bg,lastRate,reason}){if(reason==='low'){if(bg<=200)return response('hold','Continue hold',null,['After BG <100, protocol requires BG >200 mg/dL to resume at 50% of prior rate. Recheck hourly and ensure dextrose-containing fluids are running.']);return response('review','Restart after BG <100',lastRate/2,['Restart at 50% of infusion rate before BG dropped below 100. Confirm pump setting and ongoing Table 2 titration.'])}return response('review','Recheck and resume per Table 2',null,['For a hold because a calculated reduction was negative, protocol says recheck after 1 hour and resume per Table 2; it does not supply a fixed restart rate.'])}
if(typeof module!=='undefined')module.exports={band,init,adjust,restart,deltaCol};
